### ISSUE TITLE
TED-Deli Talks

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/project-ideas#21]
**BLUF:** TED talks for the not-yet-successful.

We aren't quite ready for TED, (or TEDx...) but we're definitely ready for TED-Deli. Basically we just walk to [Ted's](http://www.yelp.com/biz/teds-market-and-delicatessen-san-francisco), get sandwiches, and nerd out on health stuff...

**Comment by fureigh** [comment]
Don't forget the chili! :)

I wasn't really kidding about the recording part. We could always do it back at CfA HQ if there's too much background noise.
