### ISSUE TITLE
"EBT Near Me" – Put a map on it:  "Where can I use my EBT card?"

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/project-ideas#33]
**BLUF**: Let's scrape ebt.ca.gov's list of stores that accept EBT, search for address and Yelp reviews of said stores, and put them on a map.

---

So, already in this experiment I've decided it sucks to ask whether or not a store takes EBT. Sometimes its on the door outside, sometimes its not. I haven't been turned away yet, but the idea of being told "sorry, we don't" while holding an armful of groceries sounds terrible.

To avoid this, I visited www.ebt.ca.gov. Sure enough, there is a link that reads **"Where can I use my EBT Card?"**

When you click through, a little widget appears that allows you to search by city, ZIP, or county for establishments that accept EBT food or cash benefits. Nice. I dutifully searched for locations in San Francisco, and was presented with this:

![california ebt client website - where can i use](https://cloud.githubusercontent.com/assets/2983464/3806149/3a6bce62-1c45-11e4-920c-dbeee865cd55.png)

No links to any store website or Yelp page, no map to view their locations relative to mine. No indication as to what is available at each respective store.

Could we scrape this list of stores, search for an address or yelp review of each, and present that data with links on a map? Bonus points to be able to filter the 25+ pages of results down to those stores within walking distance.

**Comment by lippytak** [comment]
One of the earliest CfA (brigade? hack night?) projects tried to address this in another way: http://www.snapfresh.org/

It's even featured on [HSA's official site](http://www.sfhsa.org/154.htm)!

Also on that page:

> You can use this Retailer Locater link to find stores in your area that takes CalFresh benefits http://snap-load-balancer-244858692.us-east-1.elb.amazonaws.com/index.html  

= 404 error :(

**Comment by lippytak** [comment]
If you search for places that accept EBT in "San Francisco":

![screen shot 2014-08-04 at 10 18 21 pm](https://cloud.githubusercontent.com/assets/2533112/3807181/fde20f54-1c5f-11e4-9100-f63d3b7bb3b2.png)

**Comment by alanjosephwilliams** [comment]
This is actually helpful! It's not perfect but its serviceable for my purposes. 

How hard do you think it would be to get this linked to on www.ebt.ca.gov? Nigh impossible?

**Comment by lippytak** [comment]
Maybe we can do this with:
1. Kimono ([pagination or targeted crawling](https://www.kimonolabs.com/learn/pagination) to get all of CA)
2. [Send it to a Google Spreadsheet](https://www.kimonolabs.com/learn/google-sheets-addon)
3. JFMI ([here](http://www.google.com/earth/outreach/tutorials/spreadsheet3.html) or [here](https://www.mapbox.com/tilemill/docs/guides/google-docs/)?)

**Comment by alanjosephwilliams** [comment]
Sounds like its worth a shot. Kimono may not be able to toggle county selections required to get all of CA, but we should try and find out.

**Comment by greggish** [comment]
i wonder how well these listings could fit into the open referral format
https://github.com/codeforamerica/OpenReferral/blob/master/openreferral.md.

**Comment by fureigh** [comment]
Another JFMI option: [Google Fusion Tables](https://support.google.com/fusiontables/answer/2571232?hl=en), especially useful if you end up working with >1K rows.

**Comment by daguar** [comment]
I've done a bunch of things like this and the flow I like is:
- go to page on mobile browser
- click okay to the site using your location
- it shows you places near you now 

With bookmark, two-click use.

#BartMeNow

**Comment by fureigh** [comment]
Good point. You could also fork and repurpose something like [chicagoflushots.org](http://www.chicagoflushots.org), a.k.a. https://github.com/tkompare/flushots2013 and use that to handle the display. Maybe update the "which days they're open" to reflect other categories, like availability of restaurant meals or groceries

(Basically all it needs to know is where to look for a Google Fusion spreadsheet. I forked it for https://github.com/fureigh/lbcflushots; happy to discuss.)

**Comment by daguar** [comment]
This also exists: https://www.ebt.ca.gov/caebtclient/usebenefit.jsp

Also leaving the Searchable Map Template link in Issues as discussed on
Slack: http://datamade.us/civic-apps/searchable-map-template/

On Tue, Aug 5, 2014 at 12:39 PM, Fureigh notifications@github.com wrote:

> Good point. You could also fork and repurpose something like
> chicagoflushots.org http://www.chicagoflushots.org, a.k.a.
> https://github.com/tkompare/flushots2013 and use that to handle the
> display. Maybe update the "which days they're open" to reflect other
> categories, like availability of restaurant meals or groceries
> 
> (Basically all it needs to know is where to look for a Google Fusion
> spreadsheet. I forked it for https://github.com/fureigh/lbcflushots;
> happy to discuss.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/health-project-ideas/issues/33#issuecomment-51248565
> .

## 

Dave Guarino
Consultant, Health Vertical
(2013 Fellowship alumnus)
Code for America http://www.codeforamerica.org/
dave@codeforamerica.org
LinkedIn http://www.linkedin.com/in/daveguarino/ | GitHub
https://github.com/daguar/

**Comment by RebeccaCoelius** [comment]
Would be nice if we could get Yelp to include this data point as they did for food inspection scores. (And probably more useful) 

Rebecca Coelius

**Comment by fureigh** [comment]
@RebeccaCoelius: That's a great idea! Does anyone on here know who the contact was/what the process was for the food inspection scores integration?

**Comment by daguar** [comment]
It was Jack and I was kinda involved. I'd reach out I Lauren maybe to see who our contact is? I can also look through old emails to see. They prolly have already thought about it, but wrote reaching out.

**Comment by fureigh** [comment]
Started hacking on it with @alanjosephwilliams today: https://github.com/fureigh/ebt-near-me

**Comment by daguar** [comment]
:thumbsup:

**Comment by lippytak** [comment]
Fun fact: The official [CF285 CalFresh application in CA](http://www.cdss.ca.gov/cdssweb/entres/forms/English/CF285.pdf) references SnapFresh:
![screen shot 2014-08-21 at 8 33 11 am](https://cloud.githubusercontent.com/assets/2533112/3998527/9e6df1fa-2948-11e4-9307-191d08a48e89.png)

Sad fact: The link (as written) doesn't work!
![screen shot 2014-08-21 at 8 34 55 am](https://cloud.githubusercontent.com/assets/2533112/3998542/c1c9b2ec-2948-11e4-9803-260846712076.png)

http**s**://...

How long until EBT near me makes it into the CF285?

**Comment by daguar** [comment]
MORE IMPETUS!

LET'S MAKE THIS HAPPEN!!! #FIDG

On Thu, Aug 21, 2014 at 8:35 AM, Jake Solomon notifications@github.com
wrote:

> Fun fact: The official CF285 CalFresh application in CA
> http://www.cdss.ca.gov/cdssweb/entres/forms/English/CF285.pdf
> references SnapFresh:
> [image: screen shot 2014-08-21 at 8 33 11 am]
> https://cloud.githubusercontent.com/assets/2533112/3998527/9e6df1fa-2948-11e4-9307-191d08a48e89.png
> 
> Sad fact: The link (as written) doesn't work!
> [image: screen shot 2014-08-21 at 8 34 55 am]
> https://cloud.githubusercontent.com/assets/2533112/3998542/c1c9b2ec-2948-11e4-9803-260846712076.png
> 
> http**s**://...
> 
> How long until EBT near me makes it into the CF285?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/health-project-ideas/issues/33#issuecomment-52937602
> .

## 

Dave Guarino
Consultant, Health Vertical
(2013 Fellowship alumnus)
Code for America http://www.codeforamerica.org/
dave@codeforamerica.org
LinkedIn http://www.linkedin.com/in/daveguarino/ | GitHub
https://github.com/daguar/

**Comment by fureigh** [comment]
Exciting possibilities. We're workin' on it! :)

@alanjosephwilliams I know you've been talking with the SnapFresh folks... think it's worth encouraging them to [fix their mod_rewrite settings](http://stackoverflow.com/questions/8371/how-do-you-redirect-https-to-http) in the meantime?

**Comment by jmadans** [comment]
Hey @RebeccaCoelius  @fureigh @daguar. Just seeing the idea about making "Accepts EBT" a tag on Yelp reviews. My gut thinks they'll give us a flat out no, but I'd be interested in making them tell us no.

Should I reach out?

**Comment by daguar** [comment]
@jmadans — It might be an interesting starting point to get unrestricted
API access if we don't have it right now.

I also still think Factual is an interesting partner on this, since they're
just awesome people and like CFA a lot and haven't had that many cases
where they could put their platform to work on social problems (I don't
think).

On Thu, Sep 4, 2014 at 2:02 AM, Jack Madans notifications@github.com
wrote:

> Hey @RebeccaCoelius https://github.com/RebeccaCoelius @fureigh
> https://github.com/fureigh @daguar https://github.com/daguar. Just
> seeing the idea about making "Accepts EBT" a tag on Yelp reviews. My gut
> thinks they'll give us a flat out no, but I'd be interested in making them
> tell us no.
> 
> Should I reach out?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/health-project-ideas/issues/33#issuecomment-54435540
> .

## 

Dave Guarino
Consultant, Health Vertical
(2013 Fellowship alumnus)
Code for America http://www.codeforamerica.org/
dave@codeforamerica.org
LinkedIn http://www.linkedin.com/in/daveguarino/ | GitHub
https://github.com/daguar/

**Comment by fureigh** [comment]
@jmadans: I share your hunch, and I've been wondering whether waiting a little bit and being able to point to adoption numbers ("look how many people are accessing this site, looking to shop with their EBT cards!") would be helpful in making the case that including the "Accepts EBT" tag would make for a better experience for Yelp's users. What do you think?

But if per @daguar's suggestion it could lead to unrestricted API access in the meantime — which we don't have now; I've just been working with my own developer account — that'd be great too.

(Oh, P.S., as I didn't announce it here earlier: EBT Near Me is live at ebtnearme.org! :) More improvements to come, but at this point it works for all of California.)

**Comment by fureigh** [comment]
I think it's safe to close this one. The conversation and development have continued at http://www.github.com/codeforamerica/ebt-near-me.
