### ISSUE TITLE
h̶e̶a̶l̶t̶h̶ project ideas < how does that make you feel?

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/project-ideas#41]
If we remove the word 'health' then maybe this repo could just become the defacto, awesome,fun, productive, open place for CfA + brigades + everyone to generate and discuss project? Labels for content areas. Close the issue + link out to repo once the project starts. And we could even do cool things like:

> We need a few things before we can start this project:
> - [ ] A juvenile expungement lawyer
> - [ ] A Python developer (no ruby allowed)
> - [ ] One real user to validate
> - [ ] Some preliminary research on m̶a̶r̶k̶e̶t̶ impact size

[at]Channel thoughts? (@RebeccaCoelius @daguar @alanjosephwilliams @jmadans @mollymcleod @dget @fureigh)

**Comment by lippytak** [comment]
@alanjosephwilliams told me to... :)

**Comment by alanjosephwilliams** [comment]
I did indeed. Update the readme tho,
