### ISSUE TITLE
EBT/SNAP Online Payment Gateway

### ISSUE THREAD

**Issue by billypat** [codeforamerica/project-ideas#57]

**Comment by AllCard** [comment]
AllCard Payments is working on this very issue.  We are certifying a new device that will be able to take all card types, including SNAP and WIC via a mobile device, so each farmer can accept such cards at their stall without having to hunt down the market manager or use a voucher/token program.

Our program will be less expensive than other solutions such as Square, encouraging farmers to partake and become FNS approved. 

If you would like more information, please email me at fiona@allcardpayments.com

**Comment by hackandgrow** [comment]
Thanks for sharing I will email you right now.

Kind Regards,

William Pattison

www.producerun.com

Willliam Pattison
ProduceRun
Co-Founder / President

415 12th Avenue SE,
Cedar Rapids, IA 52401
USA Cell: +1 319 640 7002
Email: will@producerun.com
www.producerun.com

Follow my ProduceRun profile.
Will Pattison <http://www.producerun.com/en/users/6-will-pattison#about>

**Comment by brendanbabb** [comment]
Will extend comment, but have been seeing articles about stores getting new devices to accept Apple Pay by the fall. Is there a chance to steer towards devices that work with EBT at the same time?

**Comment by hackandgrow** [comment]
Hi Brendan,

I spoke to a company recently that is working on a mobile EBT app and I can
introduce you to them if you email me at will@producerun.com

Cheers,

Willliam Pattison
ProduceRun
Co-Founder / President

415 12th Avenue SE,
Cedar Rapids, IA 52401
USA Cell: +1 319 640 7002
Email: will@producerun.com
www.producerun.com

Follow my ProduceRun profile.
Will Pattison <http://www.producerun.com/en/users/6-will-pattison#about>
