### ISSUE TITLE
Project Monitor for Brigades

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/project-ideas#59]
#### Description

We've built some basic monitoring tools for our projects at Code for America. These are [Engine Light](https://github.com/codeforamerica/engine-light) which emails you if something looks wrong with your app, and then [Project Monitor](http://project-monitor.codeforamerica.org/) - [code](https://github.com/codeforamerica/projectmonitor) - which displays if your projects tests are passing or not.

I'd like to build these into the Brigade site as a service we provide for the civic tech movement.
#### Brigade Project Monitor

The Project Monitor would be easiest as it was just rewritten internally. I'd make a separate version that would live at http://www.codeforamerica.org/brigade/project-monitor. It should be filterable by Brigade, so that http://www.codeforamerica.org/brigade/project-monitor/Code-for-San-Francisco would show their projects.

**Comment by spjika** [comment]
How does this vary from the waffle.io tool I saw recently?

I think this is a decent example of something that could be deployed and managed for all brigades yes.

**Comment by ondrae** [comment]
The waffle thing lets you organize your GutHub Issues on a project. This would have a big red box That yiur whole Brigade could see if your tests don't pass.

**Comment by ondrae** [comment]
I built a rough prototype of this at http://brigade-projectmonitor.herokuapp.com/
That view shows all civic tech projects, while you can choose just a single Brigade too
http://brigade-projectmonitor.herokuapp.com/Chi-Hack-Night

https://github.com/codeforamerica/projectmonitor/tree/javascript

**Comment by ondrae** [comment]
Another prototype at http://www.codeforamerica.org/brigade/projects/monitor
