### ISSUE TITLE
Click that California County

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/project-ideas#75]
I need to memorize all California counties but I'm bad at memorizing things.

Let's do [Click that 'Hood](http://click-that-hood.com/) for CA counties.

Instructions: https://github.com/codeforamerica/click_that_hood/wiki/How-to-add-a-city-to-Click-That-%E2%80%99Hood

**Comment by daguar** [comment]
:+1: :shipit:

**Comment by daguar** [comment]
Doin' it.

**Comment by lippytak** [comment]
:rocket:

**Comment by daguar** [comment]
PR pending!

**Comment by daguar** [comment]
Temp deploy until PR is merged into prod:
http://click-that-hood-cacounties.herokuapp.com/california-counties

**Comment by jennymt** [comment]
I know I'm way late to this party, but the offline way I did this at my last job was: http://www.amazon.com/Izola-106-California-Shower-Curtain/dp/B002V91SYK/ref=cm_cr_pr_pdt_img_top?ie=UTF8

**Comment by lippytak** [comment]
Pretty Awesome Map
[image: Inline image 1]

**Comment by daguar** [comment]
This has been live for a while! http://click-that-hood.com/california-counties
